@startmindmap
+ OutputStream
++ ByteArrayOutputStream
++ StringBufferOutputStream
++ FileOutputStream
+++ SocketOutputStream
++ ObjectOutputStream
++ FilterOutputStream
+++ BufferedOutputStream
@endmindmap
